### ISSUE TITLE
Failed to load web3, accounts, or contract. Check console for details.

### ISSUE THREAD

**Issue by SvenMeyer** [adrianmcli/truffle-react#13]
$ cd client
$ npm run start
Compiled successfully!
You can now view client in the browser.
Local:            http://localhost:3000/
------------
localhost:3000 says
Failed to load web3, accounts, or contract. Check console for details

**Comment by adrianmcli** [comment]
Did you open it up in a browser without MetaMask? (e.g. an incognito window)

**Comment by SvenMeyer** [comment]
I used Ganache GUI (which is running on port 7545) and I changed the port in truffle.js , but did not in ./client/src/utils/getWeb3.js
Changed port to 7545 in both files, is working now in browser without MetaMask.

Why is it not (supposed to) working if MetaMask plugin is installed?

**Comment by adrianmcli** [comment]
It can work with MetaMask, but you'll have to:

1. Change the network to your local one (e.g. http://localhost:8545 or whatever port your blockchain is running on)

2. Use the mnemonic given by your Ganache/Truffle Develop to sign in to an account (so that you get test Ethers to play with).

Glad to hear it's working now!

**Comment by ZhBoKn** [comment]
> 它可以与MetaMask一起使用，但是您必须：
> 
> 1. 将网络更改为您本地的网络（例如，[http：// localhost：8545](http://localhost:8545)或您的区块链正在运行的任何端口）
> 2. 使用您的Ganache / Truffle Develop提供的助记符登录一个帐户（以便您可以使用测试以太币）。
> 
> 因此，对于开发和首次使用，我建议人们不要使用MetaMask而直接使用它。入门更容易。
> 
> 很高兴听到它现在正在工作！

I have a question that how can I change the network to my local one .I have tried the metamask port 8545,but it doesn't work at all.please help me
